#!/usr/bin/env python
import argparse
import montyhall
from montyhall import NOCHANGE, CHANGE

def run():
    parser = argparse.ArgumentParser(description="Monty Hall Problem Simulator")
    parser.add_argument('runs', type=int, help='Number of iterations')

    args = parser.parse_args()
    runs = args.runs

    print ""
    montyhall.test_strategy(runs, NOCHANGE)
    print " ======== \n"
    montyhall.test_strategy(runs, CHANGE)
    print " -------- "

if __name__ == "__main__":
    run()
